server:
  port: 8081
spring:
  datasource:
#    url: ${DB_ADDRESS:jdbc:postgresql://postgres:5432/homework_61}
    url: ${DB_ADDRESS:jdbc:postgresql://localhost:5432/homework_61}
    username: app
    password: nopasswd
    driver-class: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true

  servlet:
    multipart:
      file-size-threshold: 0
      max-file-size: 512GB

#files_directory: /storage
files_directory: ./data/files
